DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS VACATION;
DROP TABLE IF EXISTS EXAM;
DROP TABLE IF EXISTS EXAM_STUDENT;

CREATE TABLE IF NOT EXISTS STUDENT
(
    ID                     INT AUTO_INCREMENT,
    GITHUB_NAME            VARCHAR(30) NOT NULL,
    GITHUB_ID              INT NOT NULL UNIQUE,
    LEFTOVER_VACATION_TIME INT,
    CONSTRAINT STUDENT_PK
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VACATION
(
    ID         INT AUTO_INCREMENT,
    STUDENT_ID INT,
    "DATE"     DATE NOT NULL,
    "START"    TIME NOT NULL,
    "END"      TIME NOT NULL,
    REASON     VARCHAR(255) NULL,
    CONSTRAINT VACATION_PK
        PRIMARY KEY (ID, STUDENT_ID)
);

CREATE TABLE IF NOT EXISTS EXAM_STUDENT
(
    STUDENT_ID INT NOT NULL,
    EXAM_ID    INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EXAM
(
    ID      INT AUTO_INCREMENT,
    "NAME"  VARCHAR(30) NOT NULL,
    EXEMPTION_OFFSET_ONLINE      INT,
    EXEMPTION_OFFSET_OFFLINE      INT,
    "DATE"  DATE NOT NULL,
    "START" TIME NOT NULL,
    "END"   TIME NOT NULL,
    ONLINE  BOOL NOT NULL,
    CONSTRAINT EXAM_PK
        PRIMARY KEY (ID)
);